[versions]
kotlin = "1.6.20"
coroutines = "1.6.0"
okhttp = "4.9.3"
retrofit = "2.7.1"
moshi = "1.13.0"
dagger = "2.40.5"
javaxinject = "1"
okio = "3.1.0"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
dagger-compiler = {module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger"}
inject = { module = "javax.inject:javax.inject", version.ref = "javaxinject" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi"}
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
okio = { module = "com.squareup.okio:okio", version.ref = "okio"}
retrofit-core =  { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit"}

[bundles]
async = ["coroutines"]
networking = ["okhttp", "retrofit-core", "retrofit-converter-moshi", "moshi"]
io = ["okio"]
           